// Generated by CoffeeScript 1.6.3
define(['jquery', 'jmodel/topaz', 'jmodel-plugins/jquery.emerald'], function($, jm) {
  var Palettes;
  Palettes = (function() {
    function Palettes(dl, parameters, constructors) {
      var className, constructor, dd, dt,
        _this = this;
      this.parameters = parameters;
      this.constructors = constructors;
      this.dl = $(dl);
      this.dt = this.dl.children('dt');
      this.state = new jm.ObservableObject({
        current: Number,
        open: Boolean(false)
      }, {
        repeat: true
      });
      this.palettes = (function() {
        var _ref, _results;
        _ref = this.constructors;
        _results = [];
        for (className in _ref) {
          constructor = _ref[className];
          dd = this.dl.children('dd').filter(className);
          dt = dd.prev('dt');
          _results.push(new constructor(dt, dd, this));
        }
        return _results;
      }).call(this);
      this.dt.event('click').map(function(_arg) {
        var target;
        target = _arg.target;
        return Math.floor($(target).index() / 2);
      }).subscribe(function(index) {
        _this.state.current(index);
        return _this.state.open(function(x) {
          return !x;
        });
      });
      this.state.event('open').subscribe(function(open) {
        return _this.dt.each(function(index, element) {
          if (index !== _this.state.current()) {
            return $(element).removeClass('open');
          } else {
            return $(element).toggleClass('open', open);
          }
        });
      });
    }

    return Palettes;

  })();
  return {
    Palettes: Palettes
  };
});

/*
//@ sourceMappingURL=palettes.map
*/
