// Generated by CoffeeScript 1.7.1
define(['jquery', 'jmodel/topaz', 'jmodel-plugins/jquery.emerald'], function($, jm) {
  var Palettes;
  Palettes = (function() {
    function Palettes(dl, parameters, constructors) {
      var className, constructor, dd, dt;
      this.parameters = parameters;
      this.constructors = constructors;
      this.dl = $(dl);
      this.dt = this.dl.children('dt');
      this.state = new jm.ObservableObject({
        current: Number,
        open: Boolean(false)
      }, {
        repeat: true
      });
      this.palettes = (function() {
        var _ref, _results;
        _ref = this.constructors;
        _results = [];
        for (className in _ref) {
          constructor = _ref[className];
          dd = this.dl.children('dd').filter(className);
          dt = dd.prev('dt');
          _results.push(new constructor(dt, dd, this));
        }
        return _results;
      }).call(this);
      this.dt.event('click').map((function(_this) {
        return function(_arg) {
          var target;
          target = _arg.target;
          return Math.floor($(target).index() / 2);
        };
      })(this)).subscribe((function(_this) {
        return function(index) {
          _this.state.current(index);
          return _this.state.open(function(x) {
            return !x;
          });
        };
      })(this));
      this.state.event('open').subscribe((function(_this) {
        return function(open) {
          return _this.dt.each(function(index, element) {
            if (index !== _this.state.current()) {
              return $(element).removeClass('open');
            } else {
              return $(element).toggleClass('open', open);
            }
          });
        };
      })(this));
    }

    return Palettes;

  })();
  return {
    Palettes: Palettes
  };
});

//# sourceMappingURL=palettes.map
