// Generated by CoffeeScript 1.3.3

define(['jquery', 'jmodel/emerald'], function($, jm) {
  var Palettes;
  Palettes = (function() {

    function Palettes(dl, parameters, constructors) {
      var className, constructor, _ref,
        _this = this;
      this.parameters = parameters;
      this.constructors = constructors;
      this.dl = $(dl);
      _ref = this.constructors;
      for (className in _ref) {
        constructor = _ref[className];
        this.palettes = new constructor(this, className);
      }
      this.dl.children('dt').event('click').subscribe(function(_arg) {
        var target;
        target = _arg.target;
        return $(target).closest('dt').toggleClass('open');
      });
    }

    return Palettes;

  })();
  return {
    Palettes: Palettes
  };
});
