// Generated by CoffeeScript 1.3.3

define(['jquery', 'jmodel/topaz'], function($, jm) {
  var Palettes;
  Palettes = (function() {

    function Palettes(dl, parameters, constructors) {
      var className, constructor, dd, dt,
        _this = this;
      this.parameters = parameters;
      this.constructors = constructors;
      this.dl = $(dl);
      this.dt = this.dl.children('dt');
      this.state = new jm.ObservableObject({
        current: Number
      }, {
        repeat: true
      });
      this.palettes = (function() {
        var _ref, _results;
        _ref = this.constructors;
        _results = [];
        for (className in _ref) {
          constructor = _ref[className];
          dd = this.dl.children('dd').filter(className);
          dt = dd.prev('dt');
          _results.push(new constructor(dt, dd, this));
        }
        return _results;
      }).call(this);
      this.dt.event('click').map(function(_arg) {
        var target;
        target = _arg.target;
        return Math.floor($(target).index() / 2);
      }).subscribe(function(index) {
        return _this.state.current(index);
      });
      this.state.event('current').subscribe(function(current) {
        return _this.dt.toggleClass(function(index) {
          if (index === current) {
            return 'open';
          } else {
            return '';
          }
        });
      });
    }

    return Palettes;

  })();
  return {
    Palettes: Palettes
  };
});
