// Generated by CoffeeScript 1.7.1
define(function(require) {
  require('jmodel/sapphire2');
  Document.prototype.find = Element.prototype.find = function(selector) {
    return new (Set.Of(Element))(this.querySelectorAll(selector));
  };
  Set.Of(Element).fromSelector = List.Of(Element).fromSelector = function(selector) {
    return document.find(selector);
  };
  return Set.Of(Element).prototype.find = List.Of(Element).prototype.find = function(selector) {
    return new this.constructor(this.mapAll(function() {
      return this.querySelectorAll(selector);
    }));
  };
});

//# sourceMappingURL=sapphire.dom.map
