// Generated by CoffeeScript 1.7.1
define(function(require) {
  var collectionFromSelector;
  require('jmodel/sapphire2');
  collectionFromSelector = function(constructor) {
    return function(selector) {
      return new constructor(document.querySelectorAll(selector));
    };
  };
  Set.Of(Element).fromSelector = collectionFromSelector(Set.Of(Element));
  List.Of(Element).fromSelector = collectionFromSelector(List.Of(Element));
  return Document.prototype.find = Element.prototype.find = function(selector) {
    return new Set.Of(Element)(this.querySelectorAll(selector));
  };
});

//# sourceMappingURL=sapphire.dom.map
